// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://buncxmagonftfbwqg4urbf6jey.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "fantasy-exchange",
    "aws_content_delivery_bucket_region": "eu-central-1",
    "aws_content_delivery_url": "http://fantasy-exchange.s3-website.eu-central-1.amazonaws.com",
    "aws_cognito_identity_pool_id": "eu-central-1:dc535272-b90a-49a1-9ed6-988d434d3602",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_36sSPOmvk",
    "aws_user_pools_web_client_id": "6r6j27nj3kertq2jcj4vn45veu"
};


export default awsmobile;
